# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capture.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_CaptureWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Capture_MainWindow")
        MainWindow.resize(820, 570)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)

        self.Button_start = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start.setGeometry(QtCore.QRect(360, 440, 141, 61))
        self.Button_start.setFont(font)
        self.Button_start.setObjectName("Button_start")
        
        self.Button_capture = QtWidgets.QPushButton(self.centralwidget)
        self.Button_capture.setGeometry(QtCore.QRect(510, 440, 141, 61))
        self.Button_capture.setFont(font)
        self.Button_capture.setObjectName("Button_capture")
        
        self.Button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stop.setGeometry(QtCore.QRect(660, 440, 141, 61))
        self.Button_stop.setFont(font)
        self.Button_stop.setObjectName("Button_stop")


        self.label_addmember = QtWidgets.QLabel(self.centralwidget)
        self.label_addmember.setGeometry(QtCore.QRect(10, 10, 801, 391))
        self.label_addmember.setEnabled(True)
        self.label_addmember.setText("")
        self.label_addmember.setObjectName("label_addmember")
        self.label_addmember.setStyleSheet("border: 2px solid black;")

        self.label_Newname = QtWidgets.QLabel(self.centralwidget)
        self.label_Newname.setGeometry(QtCore.QRect(40, 450, 141, 35))
        
        font = QtGui.QFont()
        font.setPointSize(14)
        
        self.label_Newname.setFont(font)
        self.label_Newname.setObjectName("label_Newname")
        
        self.lineNewname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNewname.setGeometry(QtCore.QRect(190, 450, 151, 35))
        self.lineNewname.setFont(font)
        self.lineNewname.setText("")
        self.lineNewname.setObjectName("lineNewname")
        
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        MainWindow.setStyleSheet("""
            QLineEdit{
                background-color: #FFFFFF;
                border: 1px solid #C0C0C0;
                border-radius: 10px;
            }
            
            QLineEdit:hover { background-color: #eee;}
            
            QLineEdit:pressed { background-color: #ccc; }
            
            QLabel{
                color: #404040;
            }
            
            
            QPushButton{
                background-color: #00BFFF;
                color: #FFFFFF;
                border-radius: 15px;
                border: 2px solid #F0FFFF;
            }

            QPushButton:hover{
                background-color: #0077be;
                }
            
            QPushButton:pressed {
                background-color: #E9967A; color: #d6d6d6;
                }
        """)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Capture_MainWindow"))
        self.Button_start.setText(_translate("MainWindow", "START"))
        self.Button_capture.setText(_translate("MainWindow", "CAPTURE"))
        self.label_Newname.setText(_translate("MainWindow", "New member"))
        self.Button_stop.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_CaptureWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
