# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Password_MainWindow(object):
    def setupUi(self, Password_MainWindow):
        Password_MainWindow.setObjectName("Password_MainWindow")
        Password_MainWindow.resize(430, 150)
        self.centralwidget = QtWidgets.QWidget(Password_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(30, 75, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setGeometry(QtCore.QRect(150, 71, 151, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_password.setFont(font)
        self.line_password.setObjectName("line_password")
        
        self.button_enter = QtWidgets.QPushButton(self.centralwidget)
        self.button_enter.setGeometry(QtCore.QRect(310, 60, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_enter.setFont(font)
        self.button_enter.setObjectName("button_enter")
        Password_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Password_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 21))
        self.menubar.setObjectName("menubar")
        Password_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Password_MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        Password_MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(Password_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Password_MainWindow)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        
        Password_MainWindow.setStyleSheet("""
            QLineEdit{
                background-color: #FFFFFF;
                border: 1px solid #C0C0C0;
                border-radius: 10px;
            }
            
            QLineEdit:hover { background-color: #eee;}
            
            QLineEdit:pressed { background-color: #ccc; }
            
            QLabel{
                color: #404040;
            }
            
            
            QPushButton{
                background-color: #00BFFF;
                color: #FFFFFF;
                border-radius: 15px;
                border: 1px solid #00BFFF;
            }

            QPushButton:hover{
                background-color: #0077be;
                }
            
            QPushButton:pressed {
                background-color: #E9967A; color: #d6d6d6;
                }
        """)

    def retranslateUi(self, Password_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Password_MainWindow.setWindowTitle(_translate("Password_MainWindow", "Password_MainWindow"))
        self.label_password.setText(_translate("Password_MainWindow", "Password"))
        self.button_enter.setText(_translate("Password_MainWindow", "Enter"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Password_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Password_MainWindow()
    ui.setupUi(Password_MainWindow)
    Password_MainWindow.show()
    sys.exit(app.exec_())
